version: '3'

services: 
  product-service:
    build: ./product-api
    volumes:
      - ./product-api:/usr/src/app
    ports:
      - 5001:80
  
  website:
    image: php:7.0-apache
    volumes:
      - ./product-ui:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service

